import type { KingdomDashboardData } from './types';

export const kingdomDashboard: KingdomDashboardData = {
  meta: {
    title: 'Naratmal AI Kingdom Dashboard',
    subtitle:
      'Ontology-driven workflow cockpit for command routing, agent coordination, operational review, and delivery health.',
    activeScenario: 'Investor update narrative and release prep',
    ontologyVersion: 'kingdom.workflow.v0',
    lastUpdated: '2026-03-31 10:40 KST',
  },
  overview: {
    mission:
      'Keep one active kingdom command moving from intake to publishable output while exposing handoffs, waiting states, and guardrail pressure.',
    queueSummary: '8 live commands, 3 in review, 1 blocked by evidence refresh.',
    metrics: [
      { label: 'Active Commands', value: '08', delta: '+2 vs 1h', tone: 'healthy' },
      { label: 'Review Latency', value: '14m', delta: '-5m today', tone: 'healthy' },
      { label: 'Blocked Nodes', value: '02', delta: '+1 new', tone: 'watch' },
      { label: 'Runtime Drift', value: '3.2%', delta: 'within SLO', tone: 'healthy' },
    ],
  },
  workflowGraph: {
    nodes: [
      {
        id: 'intake',
        label: 'Command Intake',
        kind: 'command',
        state: 'complete',
        lane: 'Ingress',
        owner: 'Ops Secretariat',
        detail: 'Normalize prompt, classify urgency, attach context pack.',
        x: 6,
        y: 14,
        duration: '02m',
      },
      {
        id: 'ontology',
        label: 'Ontology Mapping',
        kind: 'analysis',
        state: 'complete',
        lane: 'Reasoning',
        owner: 'Chief Agent',
        detail: 'Map intent to command schema, policy surface, and delivery contract.',
        x: 30,
        y: 14,
        duration: '03m',
      },
      {
        id: 'delegation',
        label: 'Agency Delegation',
        kind: 'analysis',
        state: 'running',
        lane: 'Reasoning',
        owner: 'Chief Agent',
        detail: 'Dispatch to design, engineering, and content specialists.',
        x: 54,
        y: 14,
        duration: '06m',
      },
      {
        id: 'artifact',
        label: 'Artifact Synthesis',
        kind: 'delivery',
        state: 'queued',
        lane: 'Output',
        owner: 'Product Engineering',
        detail: 'Merge narrative, UI, and operational notes into output bundle.',
        x: 78,
        y: 14,
        duration: '09m',
      },
      {
        id: 'memory',
        label: 'Memory Update',
        kind: 'memory',
        state: 'waiting',
        lane: 'Continuity',
        owner: 'Ops Secretariat',
        detail: 'Persist lessons, next action, and state snapshot after publish.',
        x: 78,
        y: 36,
        duration: 'pending',
      },
      {
        id: 'review',
        label: 'Audit Review',
        kind: 'review',
        state: 'blocked',
        lane: 'Guardrails',
        owner: 'Audit Guard',
        detail: 'Claims need fresh source proof before external delivery approval.',
        x: 54,
        y: 36,
        duration: '11m',
      },
      {
        id: 'release',
        label: 'Release Gate',
        kind: 'delivery',
        state: 'idle',
        lane: 'Output',
        owner: 'Ops Secretariat',
        detail: 'Awaiting review release to ship the final package.',
        x: 30,
        y: 36,
        duration: 'not started',
      },
    ],
    edges: [
      { id: 'e1', from: 'intake', to: 'ontology', condition: 'default', label: 'intent classified' },
      { id: 'e2', from: 'ontology', to: 'delegation', condition: 'handoff', label: 'roles assigned' },
      { id: 'e3', from: 'delegation', to: 'artifact', condition: 'default', label: 'draft assembled' },
      { id: 'e4', from: 'delegation', to: 'review', condition: 'guardrail', label: 'external delivery' },
      { id: 'e5', from: 'review', to: 'release', condition: 'feedback', label: 'proof required' },
      { id: 'e6', from: 'release', to: 'memory', condition: 'default', label: 'publish and log' },
      { id: 'e7', from: 'artifact', to: 'memory', condition: 'handoff', label: 'state snapshot' },
    ],
  },
  agencyRoster: [
    {
      id: 'chief',
      name: 'Chief Agent',
      responsibility: 'Route commands, preserve ontology alignment, resolve handoffs.',
      availability: 'online',
      loadPercent: 82,
      queueDepth: 4,
      currentTask: 'Delegating investor update package',
      updatedAt: '10:40',
    },
    {
      id: 'ops',
      name: 'Ops Secretariat',
      responsibility: 'Intake hygiene, release operations, memory updates.',
      availability: 'online',
      loadPercent: 61,
      queueDepth: 3,
      currentTask: 'Preparing release gate checklist',
      updatedAt: '10:38',
    },
    {
      id: 'design',
      name: 'Design Studio',
      responsibility: 'Dashboard composition, visual hierarchy, narrative presentation.',
      availability: 'online',
      loadPercent: 73,
      queueDepth: 2,
      currentTask: 'Polishing workflow graph story',
      updatedAt: '10:36',
    },
    {
      id: 'engineering',
      name: 'Product Engineering',
      responsibility: 'UI implementation, system state rendering, runtime correctness.',
      availability: 'degraded',
      loadPercent: 89,
      queueDepth: 5,
      currentTask: 'Resolving evidence-feed retry jitter',
      updatedAt: '10:39',
    },
    {
      id: 'audit',
      name: 'Audit Guard',
      responsibility: 'Claim validation, release approval, policy guardrails.',
      availability: 'online',
      loadPercent: 67,
      queueDepth: 2,
      currentTask: 'Blocking unsupported market-size statement',
      updatedAt: '10:37',
    },
  ],
  conversations: [
    {
      id: 'thread-1',
      title: 'Investor update package',
      participants: ['Human', 'Chief Agent', 'Design Studio', 'Audit Guard'],
      status: 'awaiting_review',
      messages: [
        {
          id: 'm1',
          role: 'human',
          sender: 'Founder',
          timestamp: '10:12',
          summary: 'Need a dashboard-first investor update showing workflow health and shipping confidence.',
          nodeId: 'intake',
        },
        {
          id: 'm2',
          role: 'chief_agent',
          sender: 'Chief Agent',
          timestamp: '10:14',
          summary: 'Mapped request to ontology: dashboard UI, runtime state, evidence-backed release path.',
          nodeId: 'ontology',
        },
        {
          id: 'm3',
          role: 'specialist',
          sender: 'Design Studio',
          timestamp: '10:21',
          summary: 'Proposed ontology graph, operations rail, and bottleneck callouts to visualize live command flow.',
          nodeId: 'delegation',
        },
        {
          id: 'm4',
          role: 'audit_guard',
          sender: 'Audit Guard',
          timestamp: '10:32',
          summary: 'Blocked release until external-facing claims are paired with traceable proof.',
          nodeId: 'review',
        },
      ],
    },
  ],
  commandFlow: [
    {
      id: 'cmd-1048',
      title: 'Dashboard MVP build-out',
      requester: 'Founder',
      status: 'executing',
      currentNodeId: 'delegation',
      nextAction: 'Merge specialist outputs into artifact synthesis',
      assignedAgents: ['Chief Agent', 'Design Studio', 'Product Engineering'],
      targetOutcome: 'Interactive MVP screen plus design doc',
    },
    {
      id: 'cmd-1047',
      title: 'External review response',
      requester: 'Ops',
      status: 'awaiting_review',
      currentNodeId: 'review',
      nextAction: 'Attach source proof for market sizing section',
      assignedAgents: ['Audit Guard', 'Content Marketing'],
      targetOutcome: 'Release-safe response memo',
    },
    {
      id: 'cmd-1045',
      title: 'Memory sync from yesterday',
      requester: 'System',
      status: 'completed',
      currentNodeId: 'memory',
      nextAction: 'Idle',
      assignedAgents: ['Ops Secretariat'],
      targetOutcome: 'Updated continuity file',
    },
  ],
  bottlenecks: [
    {
      id: 'incident-1',
      title: 'Evidence feed lag',
      severity: 'high',
      affectedArea: 'Audit Review',
      summary: 'External proof links are stale, so the review gate cannot approve investor-facing language.',
      action: 'Refresh evidence bundle and re-run audit validation.',
    },
    {
      id: 'incident-2',
      title: 'Engineering queue saturation',
      severity: 'medium',
      affectedArea: 'Artifact Synthesis',
      summary: 'Product Engineering is near capacity and slowing graph-to-UI integration.',
      action: 'Shift one formatting task to Design Studio and reduce queue depth.',
    },
  ],
  runtimeHealth: {
    headline: 'Core orchestration is stable, but release confidence is capped by audit evidence freshness.',
    signals: [
      {
        id: 'signal-1',
        label: 'API heartbeat',
        value: '99.94%',
        tone: 'healthy',
        detail: 'Frontend and local server heartbeats match expected cadence.',
      },
      {
        id: 'signal-2',
        label: 'Event backlog',
        value: '12 items',
        tone: 'watch',
        detail: 'Backlog is acceptable but trending upward in the engineering lane.',
      },
      {
        id: 'signal-3',
        label: 'Guardrail pressure',
        value: 'High',
        tone: 'critical',
        detail: 'Audit review is actively blocking one external command.',
      },
      {
        id: 'signal-4',
        label: 'Memory write queue',
        value: '1 pending',
        tone: 'healthy',
        detail: 'Continuity write is deferred until release gate completes.',
      },
    ],
  },
  execution: {
    activeNodeId: 'delegation',
    blockedNodeIds: ['review'],
    completedNodeIds: ['intake', 'ontology'],
  },
};
